import { PortfolioImage, LookComparisonPair } from "@/types";

export const PORTFOLIO_IMAGES: PortfolioImage[] = [
  {
    id: "1",
    src: "/images/portfolio/img-01.jpg",
    alt: "Bridal makeup - Classic elegance",
    category: "bridal",
    width: 1200,
    height: 800,
    span: "wide",
  },
  {
    id: "2",
    src: "/images/portfolio/img-02.jpg",
    alt: "Editorial look - Dramatic silhouette",
    category: "editorial",
    width: 800,
    height: 1200,
    span: "tall",
  },
  {
    id: "3",
    src: "/images/portfolio/img-03.jpg",
    alt: "Party glam - Evening sparkle",
    category: "party",
    width: 800,
    height: 1200,
    span: "tall",
  },
  {
    id: "4",
    src: "/images/portfolio/img-04.jpg",
    alt: "Everyday beauty - Natural glow",
    category: "everyday",
    width: 800,
    height: 1200,
    span: "tall",
  },
  {
    id: "5",
    src: "/images/portfolio/img-05.jpg",
    alt: "Special effects - Creative artistry",
    category: "special-effects",
    width: 800,
    height: 1200,
    span: "tall",
  },
  {
    id: "6",
    src: "/images/portfolio/img-06.png",
    alt: "Bridal makeup - Romantic garden",
    category: "bridal",
    width: 800,
    height: 1200,
    span: "tall",
  },
  {
    id: "7",
    src: "/images/portfolio/img-07.jpg",
    alt: "Editorial - Magazine cover look",
    category: "editorial",
    width: 800,
    height: 1200,
    span: "tall",
  },
  {
    id: "8",
    src: "/images/portfolio/img-08.jpg",
    alt: "Signature look - Professional artistry",
    category: "editorial",
    width: 1200,
    height: 800,
    span: "wide",
  },
  {
    id: "9",
    src: "/images/portfolio/img-09.jpg",
    alt: "Party glam - Red carpet ready",
    category: "party",
    width: 800,
    height: 1200,
    span: "tall",
  },
  {
    id: "10",
    src: "/images/portfolio/img-10.png",
    alt: "Special effects - Halloween",
    category: "special-effects",
    width: 800,
    height: 1200,
    span: "tall",
  },
  {
    id: "11",
    src: "/images/portfolio/img-11.png",
    alt: "Everyday beauty - Office ready",
    category: "everyday",
    width: 800,
    height: 1200,
    span: "tall",
  },
];

export const FEATURED_IMAGES = PORTFOLIO_IMAGES.slice(0, 8);

export const LOOK_COMPARISON_PAIRS: LookComparisonPair[] = [
  {
    id: "lc1",
    left: "/images/portfolio/img-02.jpg",
    right: "/images/portfolio/img-03.jpg",
    leftLabel: "Soft Glam",
    rightLabel: "Bold Glam",
    alt: "Bridal looks",
  },
  {
    id: "lc2",
    left: "/images/portfolio/img-04.jpg",
    right: "/images/portfolio/img-05.jpg",
    leftLabel: "Day Look",
    rightLabel: "Evening Look",
    alt: "Editorial styles",
  },
  {
    id: "lc3",
    left: "/images/portfolio/img-06.png",
    right: "/images/portfolio/img-07.jpg",
    leftLabel: "Natural",
    rightLabel: "Dramatic",
    alt: "Everyday to glam",
  },
];
